### ISSUE TITLE
Application doesn't download any documents

### ISSUE THREAD

**Issue by vdmitriev90** [insane-person/ALPFreedom#2]
Application doesn't download any documents. Please, see attached screenshots.
![image](https://user-images.githubusercontent.com/15127902/168635530-f4e58575-770b-4684-8608-3ec0ef9a49c9.png)

**Comment by insane-person** [comment]
@vdmitriev90 The problem was caused by a data format change from the federation site. Fixed, can be used.

**Comment by vdmitriev90** [comment]
Now it works. Thank You!
